GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicm1lbiIsImlhdCI6MTc2NjE0MzI0M30.Stbj5w-ATuQCZkPS_65znqQTba037iWBkphJYHbKxdE
###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "rmen"
}